repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: name-tests-test
        args: ['--pytest-test-first']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
    - id: mypy
      args: ["--ignore-missing-imports", "--check-untyped-defs"]
      additional_dependencies: [ types-PyYAML==6.0.12.3, types-requests==2.31.0.9, types-tabulate ]
